./bin/Release/simple_test ./test/CUTE_examples/hs071
./bin/Release/simple_test ./test/CUTE_examples/hs072
./bin/Release/simple_test ./test/CUTE_examples/hs073
./bin/Release/simple_test ./test/CUTE_examples/hs074
./bin/Release/simple_test ./test/CUTE_examples/hs075
./bin/Release/simple_test ./test/CUTE_examples/hs076
./bin/Release/simple_test ./test/CUTE_examples/hs077
./bin/Release/simple_test ./test/CUTE_examples/hs078
./bin/Release/simple_test ./test/CUTE_examples/hs079
./bin/Release/simple_test ./test/CUTE_examples/hs080
./bin/Release/simple_test ./test/CUTE_examples/hs081
./bin/Release/simple_test ./test/CUTE_examples/hs082
./bin/Release/simple_test ./test/CUTE_examples/hs083
./bin/Release/simple_test ./test/CUTE_examples/hs084
./bin/Release/simple_test ./test/CUTE_examples/hs085
./bin/Release/simple_test ./test/CUTE_examples/hs086
./bin/Release/simple_test ./test/CUTE_examples/hs087
./bin/Release/simple_test ./test/CUTE_examples/hs088
./bin/Release/simple_test ./test/CUTE_examples/hs089
./bin/Release/simple_test ./test/CUTE_examples/hs090
./bin/Release/simple_test ./test/CUTE_examples/hs091
./bin/Release/simple_test ./test/CUTE_examples/hs092
./bin/Release/simple_test ./test/CUTE_examples/hs093
./bin/Release/simple_test ./test/CUTE_examples/hs095
./bin/Release/simple_test ./test/CUTE_examples/hs096
./bin/Release/simple_test ./test/CUTE_examples/hs097
./bin/Release/simple_test ./test/CUTE_examples/hs098
./bin/Release/simple_test ./test/CUTE_examples/hs099
./bin/Release/simple_test ./test/CUTE_examples/hs100
./bin/Release/simple_test ./test/CUTE_examples/hs100lnp.nl
./bin/Release/simple_test ./test/CUTE_examples/hs100mod.nl
./bin/Release/simple_test ./test/CUTE_examples/hs102
./bin/Release/simple_test ./test/CUTE_examples/hs103
./bin/Release/simple_test ./test/CUTE_examples/hs104
./bin/Release/simple_test ./test/CUTE_examples/hs105
./bin/Release/simple_test ./test/CUTE_examples/hs106
./bin/Release/simple_test ./test/CUTE_examples/hs107
./bin/Release/simple_test ./test/CUTE_examples/hs108
./bin/Release/simple_test ./test/CUTE_examples/hs109
./bin/Release/simple_test ./test/CUTE_examples/hs110
./bin/Release/simple_test ./test/CUTE_examples/hs111lnp.nl
./bin/Release/simple_test ./test/CUTE_examples/hs111.nl
./bin/Release/simple_test ./test/CUTE_examples/hs112.nl
./bin/Release/simple_test ./test/CUTE_examples/hs113.nl
./bin/Release/simple_test ./test/CUTE_examples/hs114.nl
./bin/Release/simple_test ./test/CUTE_examples/hs116.nl
./bin/Release/simple_test ./test/CUTE_examples/hs117.nl
./bin/Release/simple_test ./test/CUTE_examples/hs118.nl
./bin/Release/simple_test ./test/CUTE_examples/hs119.nl
./bin/Release/simple_test ./test/CUTE_examples/hs21mod.nl
./bin/Release/simple_test ./test/CUTE_examples/hs268.nl
./bin/Release/simple_test ./test/CUTE_examples/hs35mod.nl
./bin/Release/simple_test ./test/CUTE_examples/hs3mod.nl
./bin/Release/simple_test ./test/CUTE_examples/hs44new.nl
./bin/Release/simple_test ./test/CUTE_examples/hs99exp.nl



