./bin/simple_test ./test/CUTE_examples/hs001
./bin/simple_test ./test/CUTE_examples/hs002
./bin/simple_test ./test/CUTE_examples/hs003
./bin/simple_test ./test/CUTE_examples/hs004
./bin/simple_test ./test/CUTE_examples/hs005
./bin/simple_test ./test/CUTE_examples/hs006
./bin/simple_test ./test/CUTE_examples/hs007
./bin/simple_test ./test/CUTE_examples/hs008
./bin/simple_test ./test/CUTE_examples/hs009
./bin/simple_test ./test/CUTE_examples/hs010
./bin/simple_test ./test/CUTE_examples/hs011
./bin/simple_test ./test/CUTE_examples/hs012
./bin/simple_test ./test/CUTE_examples/hs013
./bin/simple_test ./test/CUTE_examples/hs014
./bin/simple_test ./test/CUTE_examples/hs015
./bin/simple_test ./test/CUTE_examples/hs016
./bin/simple_test ./test/CUTE_examples/hs017
./bin/simple_test ./test/CUTE_examples/hs018
./bin/simple_test ./test/CUTE_examples/hs019
./bin/simple_test ./test/CUTE_examples/hs020
./bin/simple_test ./test/CUTE_examples/hs021
./bin/simple_test ./test/CUTE_examples/hs022
./bin/simple_test ./test/CUTE_examples/hs023
./bin/simple_test ./test/CUTE_examples/hs024
./bin/simple_test ./test/CUTE_examples/hs025
./bin/simple_test ./test/CUTE_examples/hs026
./bin/simple_test ./test/CUTE_examples/hs027
./bin/simple_test ./test/CUTE_examples/hs028
./bin/simple_test ./test/CUTE_examples/hs029
./bin/simple_test ./test/CUTE_examples/hs030
./bin/simple_test ./test/CUTE_examples/hs031
./bin/simple_test ./test/CUTE_examples/hs032
./bin/simple_test ./test/CUTE_examples/hs033
./bin/simple_test ./test/CUTE_examples/hs034
./bin/simple_test ./test/CUTE_examples/hs035
./bin/simple_test ./test/CUTE_examples/hs036
./bin/simple_test ./test/CUTE_examples/hs037
./bin/simple_test ./test/CUTE_examples/hs038
./bin/simple_test ./test/CUTE_examples/hs039
./bin/simple_test ./test/CUTE_examples/hs040
./bin/simple_test ./test/CUTE_examples/hs041
./bin/simple_test ./test/CUTE_examples/hs042
./bin/simple_test ./test/CUTE_examples/hs043
./bin/simple_test ./test/CUTE_examples/hs044
./bin/simple_test ./test/CUTE_examples/hs045
./bin/simple_test ./test/CUTE_examples/hs046
./bin/simple_test ./test/CUTE_examples/hs047
./bin/simple_test ./test/CUTE_examples/hs048
./bin/simple_test ./test/CUTE_examples/hs049
./bin/simple_test ./test/CUTE_examples/hs050
./bin/simple_test ./test/CUTE_examples/hs051
./bin/simple_test ./test/CUTE_examples/hs052
./bin/simple_test ./test/CUTE_examples/hs053
./bin/simple_test ./test/CUTE_examples/hs054
./bin/simple_test ./test/CUTE_examples/hs055
./bin/simple_test ./test/CUTE_examples/hs056
./bin/simple_test ./test/CUTE_examples/hs057
./bin/simple_test ./test/CUTE_examples/hs059
./bin/simple_test ./test/CUTE_examples/hs060
./bin/simple_test ./test/CUTE_examples/hs061
./bin/simple_test ./test/CUTE_examples/hs062
./bin/simple_test ./test/CUTE_examples/hs063
./bin/simple_test ./test/CUTE_examples/hs064
./bin/simple_test ./test/CUTE_examples/hs065
./bin/simple_test ./test/CUTE_examples/hs066
./bin/simple_test ./test/CUTE_examples/hs067
./bin/simple_test ./test/CUTE_examples/hs070
