/Users/xinyiluo/Dropbox/Research/SQPhotstart/build/bin/simple_test /Users/xinyiluo/Dropbox/Research/SQPhotstart/test/CUTE_examples/hs001
/Users/xinyiluo/Dropbox/Research/SQPhotstart/build/bin/simple_test /Users/xinyiluo/Dropbox/Research/SQPhotstart/test/CUTE_examples/hs002
/Users/xinyiluo/Dropbox/Research/SQPhotstart/build/bin/simple_test /Users/xinyiluo/Dropbox/Research/SQPhotstart/test/CUTE_examples/hs003
/Users/xinyiluo/Dropbox/Research/SQPhotstart/build/bin/simple_test /Users/xinyiluo/Dropbox/Research/SQPhotstart/test/CUTE_examples/hs004
/Users/xinyiluo/Dropbox/Research/SQPhotstart/build/bin/simple_test /Users/xinyiluo/Dropbox/Research/SQPhotstart/test/CUTE_examples/hs005
/Users/xinyiluo/Dropbox/Research/SQPhotstart/build/bin/simple_test /Users/xinyiluo/Dropbox/Research/SQPhotstart/test/CUTE_examples/hs006
/Users/xinyiluo/Dropbox/Research/SQPhotstart/build/bin/simple_test /Users/xinyiluo/Dropbox/Research/SQPhotstart/test/CUTE_examples/hs007
/Users/xinyiluo/Dropbox/Research/SQPhotstart/build/bin/simple_test /Users/xinyiluo/Dropbox/Research/SQPhotstart/test/CUTE_examples/hs008
/Users/xinyiluo/Dropbox/Research/SQPhotstart/build/bin/simple_test /Users/xinyiluo/Dropbox/Research/SQPhotstart/test/CUTE_examples/hs009
/Users/xinyiluo/Dropbox/Research/SQPhotstart/build/bin/simple_test /Users/xinyiluo/Dropbox/Research/SQPhotstart/test/CUTE_examples/hs010
/Users/xinyiluo/Dropbox/Research/SQPhotstart/build/bin/simple_test /Users/xinyiluo/Dropbox/Research/SQPhotstart/test/CUTE_examples/hs011
/Users/xinyiluo/Dropbox/Research/SQPhotstart/build/bin/simple_test /Users/xinyiluo/Dropbox/Research/SQPhotstart/test/CUTE_examples/hs012
/Users/xinyiluo/Dropbox/Research/SQPhotstart/build/bin/simple_test /Users/xinyiluo/Dropbox/Research/SQPhotstart/test/CUTE_examples/hs013
/Users/xinyiluo/Dropbox/Research/SQPhotstart/build/bin/simple_test /Users/xinyiluo/Dropbox/Research/SQPhotstart/test/CUTE_examples/hs014
/Users/xinyiluo/Dropbox/Research/SQPhotstart/build/bin/simple_test /Users/xinyiluo/Dropbox/Research/SQPhotstart/test/CUTE_examples/hs015
/Users/xinyiluo/Dropbox/Research/SQPhotstart/build/bin/simple_test /Users/xinyiluo/Dropbox/Research/SQPhotstart/test/CUTE_examples/hs016
/Users/xinyiluo/Dropbox/Research/SQPhotstart/build/bin/simple_test /Users/xinyiluo/Dropbox/Research/SQPhotstart/test/CUTE_examples/hs017
/Users/xinyiluo/Dropbox/Research/SQPhotstart/build/bin/simple_test /Users/xinyiluo/Dropbox/Research/SQPhotstart/test/CUTE_examples/hs018
/Users/xinyiluo/Dropbox/Research/SQPhotstart/build/bin/simple_test /Users/xinyiluo/Dropbox/Research/SQPhotstart/test/CUTE_examples/hs019
/Users/xinyiluo/Dropbox/Research/SQPhotstart/build/bin/simple_test /Users/xinyiluo/Dropbox/Research/SQPhotstart/test/CUTE_examples/hs020
/Users/xinyiluo/Dropbox/Research/SQPhotstart/build/bin/simple_test /Users/xinyiluo/Dropbox/Research/SQPhotstart/test/CUTE_examples/hs021
/Users/xinyiluo/Dropbox/Research/SQPhotstart/build/bin/simple_test /Users/xinyiluo/Dropbox/Research/SQPhotstart/test/CUTE_examples/hs022
/Users/xinyiluo/Dropbox/Research/SQPhotstart/build/bin/simple_test /Users/xinyiluo/Dropbox/Research/SQPhotstart/test/CUTE_examples/hs023
/Users/xinyiluo/Dropbox/Research/SQPhotstart/build/bin/simple_test /Users/xinyiluo/Dropbox/Research/SQPhotstart/test/CUTE_examples/hs024
/Users/xinyiluo/Dropbox/Research/SQPhotstart/build/bin/simple_test /Users/xinyiluo/Dropbox/Research/SQPhotstart/test/CUTE_examples/hs025
/Users/xinyiluo/Dropbox/Research/SQPhotstart/build/bin/simple_test /Users/xinyiluo/Dropbox/Research/SQPhotstart/test/CUTE_examples/hs026
/Users/xinyiluo/Dropbox/Research/SQPhotstart/build/bin/simple_test /Users/xinyiluo/Dropbox/Research/SQPhotstart/test/CUTE_examples/hs027
/Users/xinyiluo/Dropbox/Research/SQPhotstart/build/bin/simple_test /Users/xinyiluo/Dropbox/Research/SQPhotstart/test/CUTE_examples/hs028
/Users/xinyiluo/Dropbox/Research/SQPhotstart/build/bin/simple_test /Users/xinyiluo/Dropbox/Research/SQPhotstart/test/CUTE_examples/hs029
/Users/xinyiluo/Dropbox/Research/SQPhotstart/build/bin/simple_test /Users/xinyiluo/Dropbox/Research/SQPhotstart/test/CUTE_examples/hs030
/Users/xinyiluo/Dropbox/Research/SQPhotstart/build/bin/simple_test /Users/xinyiluo/Dropbox/Research/SQPhotstart/test/CUTE_examples/hs031
/Users/xinyiluo/Dropbox/Research/SQPhotstart/build/bin/simple_test /Users/xinyiluo/Dropbox/Research/SQPhotstart/test/CUTE_examples/hs032
/Users/xinyiluo/Dropbox/Research/SQPhotstart/build/bin/simple_test /Users/xinyiluo/Dropbox/Research/SQPhotstart/test/CUTE_examples/hs033
/Users/xinyiluo/Dropbox/Research/SQPhotstart/build/bin/simple_test /Users/xinyiluo/Dropbox/Research/SQPhotstart/test/CUTE_examples/hs034
/Users/xinyiluo/Dropbox/Research/SQPhotstart/build/bin/simple_test /Users/xinyiluo/Dropbox/Research/SQPhotstart/test/CUTE_examples/hs035
/Users/xinyiluo/Dropbox/Research/SQPhotstart/build/bin/simple_test /Users/xinyiluo/Dropbox/Research/SQPhotstart/test/CUTE_examples/hs036
/Users/xinyiluo/Dropbox/Research/SQPhotstart/build/bin/simple_test /Users/xinyiluo/Dropbox/Research/SQPhotstart/test/CUTE_examples/hs037
/Users/xinyiluo/Dropbox/Research/SQPhotstart/build/bin/simple_test /Users/xinyiluo/Dropbox/Research/SQPhotstart/test/CUTE_examples/hs038
/Users/xinyiluo/Dropbox/Research/SQPhotstart/build/bin/simple_test /Users/xinyiluo/Dropbox/Research/SQPhotstart/test/CUTE_examples/hs039
/Users/xinyiluo/Dropbox/Research/SQPhotstart/build/bin/simple_test /Users/xinyiluo/Dropbox/Research/SQPhotstart/test/CUTE_examples/hs040
/Users/xinyiluo/Dropbox/Research/SQPhotstart/build/bin/simple_test /Users/xinyiluo/Dropbox/Research/SQPhotstart/test/CUTE_examples/hs041
/Users/xinyiluo/Dropbox/Research/SQPhotstart/build/bin/simple_test /Users/xinyiluo/Dropbox/Research/SQPhotstart/test/CUTE_examples/hs042
/Users/xinyiluo/Dropbox/Research/SQPhotstart/build/bin/simple_test /Users/xinyiluo/Dropbox/Research/SQPhotstart/test/CUTE_examples/hs043
/Users/xinyiluo/Dropbox/Research/SQPhotstart/build/bin/simple_test /Users/xinyiluo/Dropbox/Research/SQPhotstart/test/CUTE_examples/hs044
/Users/xinyiluo/Dropbox/Research/SQPhotstart/build/bin/simple_test /Users/xinyiluo/Dropbox/Research/SQPhotstart/test/CUTE_examples/hs045
/Users/xinyiluo/Dropbox/Research/SQPhotstart/build/bin/simple_test /Users/xinyiluo/Dropbox/Research/SQPhotstart/test/CUTE_examples/hs046
/Users/xinyiluo/Dropbox/Research/SQPhotstart/build/bin/simple_test /Users/xinyiluo/Dropbox/Research/SQPhotstart/test/CUTE_examples/hs047
/Users/xinyiluo/Dropbox/Research/SQPhotstart/build/bin/simple_test /Users/xinyiluo/Dropbox/Research/SQPhotstart/test/CUTE_examples/hs048
/Users/xinyiluo/Dropbox/Research/SQPhotstart/build/bin/simple_test /Users/xinyiluo/Dropbox/Research/SQPhotstart/test/CUTE_examples/hs049
/Users/xinyiluo/Dropbox/Research/SQPhotstart/build/bin/simple_test /Users/xinyiluo/Dropbox/Research/SQPhotstart/test/CUTE_examples/hs050
/Users/xinyiluo/Dropbox/Research/SQPhotstart/build/bin/simple_test /Users/xinyiluo/Dropbox/Research/SQPhotstart/test/CUTE_examples/hs051
/Users/xinyiluo/Dropbox/Research/SQPhotstart/build/bin/simple_test /Users/xinyiluo/Dropbox/Research/SQPhotstart/test/CUTE_examples/hs052
/Users/xinyiluo/Dropbox/Research/SQPhotstart/build/bin/simple_test /Users/xinyiluo/Dropbox/Research/SQPhotstart/test/CUTE_examples/hs053
/Users/xinyiluo/Dropbox/Research/SQPhotstart/build/bin/simple_test /Users/xinyiluo/Dropbox/Research/SQPhotstart/test/CUTE_examples/hs054
/Users/xinyiluo/Dropbox/Research/SQPhotstart/build/bin/simple_test /Users/xinyiluo/Dropbox/Research/SQPhotstart/test/CUTE_examples/hs055
/Users/xinyiluo/Dropbox/Research/SQPhotstart/build/bin/simple_test /Users/xinyiluo/Dropbox/Research/SQPhotstart/test/CUTE_examples/hs056
/Users/xinyiluo/Dropbox/Research/SQPhotstart/build/bin/simple_test /Users/xinyiluo/Dropbox/Research/SQPhotstart/test/CUTE_examples/hs057
/Users/xinyiluo/Dropbox/Research/SQPhotstart/build/bin/simple_test /Users/xinyiluo/Dropbox/Research/SQPhotstart/test/CUTE_examples/hs059
/Users/xinyiluo/Dropbox/Research/SQPhotstart/build/bin/simple_test /Users/xinyiluo/Dropbox/Research/SQPhotstart/test/CUTE_examples/hs060
/Users/xinyiluo/Dropbox/Research/SQPhotstart/build/bin/simple_test /Users/xinyiluo/Dropbox/Research/SQPhotstart/test/CUTE_examples/hs061
/Users/xinyiluo/Dropbox/Research/SQPhotstart/build/bin/simple_test /Users/xinyiluo/Dropbox/Research/SQPhotstart/test/CUTE_examples/hs062
/Users/xinyiluo/Dropbox/Research/SQPhotstart/build/bin/simple_test /Users/xinyiluo/Dropbox/Research/SQPhotstart/test/CUTE_examples/hs063
/Users/xinyiluo/Dropbox/Research/SQPhotstart/build/bin/simple_test /Users/xinyiluo/Dropbox/Research/SQPhotstart/test/CUTE_examples/hs064
/Users/xinyiluo/Dropbox/Research/SQPhotstart/build/bin/simple_test /Users/xinyiluo/Dropbox/Research/SQPhotstart/test/CUTE_examples/hs065
/Users/xinyiluo/Dropbox/Research/SQPhotstart/build/bin/simple_test /Users/xinyiluo/Dropbox/Research/SQPhotstart/test/CUTE_examples/hs066
/Users/xinyiluo/Dropbox/Research/SQPhotstart/build/bin/simple_test /Users/xinyiluo/Dropbox/Research/SQPhotstart/test/CUTE_examples/hs067
/Users/xinyiluo/Dropbox/Research/SQPhotstart/build/bin/simple_test /Users/xinyiluo/Dropbox/Research/SQPhotstart/test/CUTE_examples/hs070
/Users/xinyiluo/Dropbox/Research/SQPhotstart/build/bin/simple_test /Users/xinyiluo/Dropbox/Research/SQPhotstart/test/CUTE_examples/hs071
/Users/xinyiluo/Dropbox/Research/SQPhotstart/build/bin/simple_test /Users/xinyiluo/Dropbox/Research/SQPhotstart/test/CUTE_examples/hs072
/Users/xinyiluo/Dropbox/Research/SQPhotstart/build/bin/simple_test /Users/xinyiluo/Dropbox/Research/SQPhotstart/test/CUTE_examples/hs073
/Users/xinyiluo/Dropbox/Research/SQPhotstart/build/bin/simple_test /Users/xinyiluo/Dropbox/Research/SQPhotstart/test/CUTE_examples/hs074
/Users/xinyiluo/Dropbox/Research/SQPhotstart/build/bin/simple_test /Users/xinyiluo/Dropbox/Research/SQPhotstart/test/CUTE_examples/hs075
/Users/xinyiluo/Dropbox/Research/SQPhotstart/build/bin/simple_test /Users/xinyiluo/Dropbox/Research/SQPhotstart/test/CUTE_examples/hs076
/Users/xinyiluo/Dropbox/Research/SQPhotstart/build/bin/simple_test /Users/xinyiluo/Dropbox/Research/SQPhotstart/test/CUTE_examples/hs077
/Users/xinyiluo/Dropbox/Research/SQPhotstart/build/bin/simple_test /Users/xinyiluo/Dropbox/Research/SQPhotstart/test/CUTE_examples/hs078
/Users/xinyiluo/Dropbox/Research/SQPhotstart/build/bin/simple_test /Users/xinyiluo/Dropbox/Research/SQPhotstart/test/CUTE_examples/hs079
/Users/xinyiluo/Dropbox/Research/SQPhotstart/build/bin/simple_test /Users/xinyiluo/Dropbox/Research/SQPhotstart/test/CUTE_examples/hs080
/Users/xinyiluo/Dropbox/Research/SQPhotstart/build/bin/simple_test /Users/xinyiluo/Dropbox/Research/SQPhotstart/test/CUTE_examples/hs081
/Users/xinyiluo/Dropbox/Research/SQPhotstart/build/bin/simple_test /Users/xinyiluo/Dropbox/Research/SQPhotstart/test/CUTE_examples/hs083
/Users/xinyiluo/Dropbox/Research/SQPhotstart/build/bin/simple_test /Users/xinyiluo/Dropbox/Research/SQPhotstart/test/CUTE_examples/hs084
/Users/xinyiluo/Dropbox/Research/SQPhotstart/build/bin/simple_test /Users/xinyiluo/Dropbox/Research/SQPhotstart/test/CUTE_examples/hs085
/Users/xinyiluo/Dropbox/Research/SQPhotstart/build/bin/simple_test /Users/xinyiluo/Dropbox/Research/SQPhotstart/test/CUTE_examples/hs086
/Users/xinyiluo/Dropbox/Research/SQPhotstart/build/bin/simple_test /Users/xinyiluo/Dropbox/Research/SQPhotstart/test/CUTE_examples/hs087
/Users/xinyiluo/Dropbox/Research/SQPhotstart/build/bin/simple_test /Users/xinyiluo/Dropbox/Research/SQPhotstart/test/CUTE_examples/hs088
/Users/xinyiluo/Dropbox/Research/SQPhotstart/build/bin/simple_test /Users/xinyiluo/Dropbox/Research/SQPhotstart/test/CUTE_examples/hs089
/Users/xinyiluo/Dropbox/Research/SQPhotstart/build/bin/simple_test /Users/xinyiluo/Dropbox/Research/SQPhotstart/test/CUTE_examples/hs090
/Users/xinyiluo/Dropbox/Research/SQPhotstart/build/bin/simple_test /Users/xinyiluo/Dropbox/Research/SQPhotstart/test/CUTE_examples/hs091
/Users/xinyiluo/Dropbox/Research/SQPhotstart/build/bin/simple_test /Users/xinyiluo/Dropbox/Research/SQPhotstart/test/CUTE_examples/hs092
/Users/xinyiluo/Dropbox/Research/SQPhotstart/build/bin/simple_test /Users/xinyiluo/Dropbox/Research/SQPhotstart/test/CUTE_examples/hs093
/Users/xinyiluo/Dropbox/Research/SQPhotstart/build/bin/simple_test /Users/xinyiluo/Dropbox/Research/SQPhotstart/test/CUTE_examples/hs095
/Users/xinyiluo/Dropbox/Research/SQPhotstart/build/bin/simple_test /Users/xinyiluo/Dropbox/Research/SQPhotstart/test/CUTE_examples/hs096
/Users/xinyiluo/Dropbox/Research/SQPhotstart/build/bin/simple_test /Users/xinyiluo/Dropbox/Research/SQPhotstart/test/CUTE_examples/hs097
/Users/xinyiluo/Dropbox/Research/SQPhotstart/build/bin/simple_test /Users/xinyiluo/Dropbox/Research/SQPhotstart/test/CUTE_examples/hs098
/Users/xinyiluo/Dropbox/Research/SQPhotstart/build/bin/simple_test /Users/xinyiluo/Dropbox/Research/SQPhotstart/test/CUTE_examples/hs099
/Users/xinyiluo/Dropbox/Research/SQPhotstart/build/bin/simple_test /Users/xinyiluo/Dropbox/Research/SQPhotstart/test/CUTE_examples/hs100
/Users/xinyiluo/Dropbox/Research/SQPhotstart/build/bin/simple_test /Users/xinyiluo/Dropbox/Research/SQPhotstart/test/CUTE_examples/hs100lnp.nl
/Users/xinyiluo/Dropbox/Research/SQPhotstart/build/bin/simple_test /Users/xinyiluo/Dropbox/Research/SQPhotstart/test/CUTE_examples/hs100mod.nl
/Users/xinyiluo/Dropbox/Research/SQPhotstart/build/bin/simple_test /Users/xinyiluo/Dropbox/Research/SQPhotstart/test/CUTE_examples/hs102
/Users/xinyiluo/Dropbox/Research/SQPhotstart/build/bin/simple_test /Users/xinyiluo/Dropbox/Research/SQPhotstart/test/CUTE_examples/hs103
/Users/xinyiluo/Dropbox/Research/SQPhotstart/build/bin/simple_test /Users/xinyiluo/Dropbox/Research/SQPhotstart/test/CUTE_examples/hs104
/Users/xinyiluo/Dropbox/Research/SQPhotstart/build/bin/simple_test /Users/xinyiluo/Dropbox/Research/SQPhotstart/test/CUTE_examples/hs105
/Users/xinyiluo/Dropbox/Research/SQPhotstart/build/bin/simple_test /Users/xinyiluo/Dropbox/Research/SQPhotstart/test/CUTE_examples/hs106
/Users/xinyiluo/Dropbox/Research/SQPhotstart/build/bin/simple_test /Users/xinyiluo/Dropbox/Research/SQPhotstart/test/CUTE_examples/hs107
/Users/xinyiluo/Dropbox/Research/SQPhotstart/build/bin/simple_test /Users/xinyiluo/Dropbox/Research/SQPhotstart/test/CUTE_examples/hs108
/Users/xinyiluo/Dropbox/Research/SQPhotstart/build/bin/simple_test /Users/xinyiluo/Dropbox/Research/SQPhotstart/test/CUTE_examples/hs109
/Users/xinyiluo/Dropbox/Research/SQPhotstart/build/bin/simple_test /Users/xinyiluo/Dropbox/Research/SQPhotstart/test/CUTE_examples/hs110
/Users/xinyiluo/Dropbox/Research/SQPhotstart/build/bin/simple_test /Users/xinyiluo/Dropbox/Research/SQPhotstart/test/CUTE_examples/hs111lnp.nl
/Users/xinyiluo/Dropbox/Research/SQPhotstart/build/bin/simple_test /Users/xinyiluo/Dropbox/Research/SQPhotstart/test/CUTE_examples/hs111.nl
/Users/xinyiluo/Dropbox/Research/SQPhotstart/build/bin/simple_test /Users/xinyiluo/Dropbox/Research/SQPhotstart/test/CUTE_examples/hs112.nl
/Users/xinyiluo/Dropbox/Research/SQPhotstart/build/bin/simple_test /Users/xinyiluo/Dropbox/Research/SQPhotstart/test/CUTE_examples/hs113.nl
/Users/xinyiluo/Dropbox/Research/SQPhotstart/build/bin/simple_test /Users/xinyiluo/Dropbox/Research/SQPhotstart/test/CUTE_examples/hs114.nl
/Users/xinyiluo/Dropbox/Research/SQPhotstart/build/bin/simple_test /Users/xinyiluo/Dropbox/Research/SQPhotstart/test/CUTE_examples/hs116.nl
/Users/xinyiluo/Dropbox/Research/SQPhotstart/build/bin/simple_test /Users/xinyiluo/Dropbox/Research/SQPhotstart/test/CUTE_examples/hs117.nl
/Users/xinyiluo/Dropbox/Research/SQPhotstart/build/bin/simple_test /Users/xinyiluo/Dropbox/Research/SQPhotstart/test/CUTE_examples/hs118.nl
/Users/xinyiluo/Dropbox/Research/SQPhotstart/build/bin/simple_test /Users/xinyiluo/Dropbox/Research/SQPhotstart/test/CUTE_examples/hs119.nl
/Users/xinyiluo/Dropbox/Research/SQPhotstart/build/bin/simple_test /Users/xinyiluo/Dropbox/Research/SQPhotstart/test/CUTE_examples/hs21mod.nl
/Users/xinyiluo/Dropbox/Research/SQPhotstart/build/bin/simple_test /Users/xinyiluo/Dropbox/Research/SQPhotstart/test/CUTE_examples/hs268.nl
/Users/xinyiluo/Dropbox/Research/SQPhotstart/build/bin/simple_test /Users/xinyiluo/Dropbox/Research/SQPhotstart/test/CUTE_examples/hs35mod.nl
/Users/xinyiluo/Dropbox/Research/SQPhotstart/build/bin/simple_test /Users/xinyiluo/Dropbox/Research/SQPhotstart/test/CUTE_examples/hs3mod.nl
/Users/xinyiluo/Dropbox/Research/SQPhotstart/build/bin/simple_test /Users/xinyiluo/Dropbox/Research/SQPhotstart/test/CUTE_examples/hs44new.nl
/Users/xinyiluo/Dropbox/Research/SQPhotstart/build/bin/simple_test /Users/xinyiluo/Dropbox/Research/SQPhotstart/test/CUTE_examples/hs99exp.nl
