~/Research/SQPhotstart/bin/Release/simple_test ~/Research/SQPhotstart/test/CUTE_examples/hs001
~/Research/SQPhotstart/bin/Release/simple_test ~/Research/SQPhotstart/test/CUTE_examples/hs002
~/Research/SQPhotstart/bin/Release/simple_test ~/Research/SQPhotstart/test/CUTE_examples/hs003
~/Research/SQPhotstart/bin/Release/simple_test ~/Research/SQPhotstart/test/CUTE_examples/hs004
~/Research/SQPhotstart/bin/Release/simple_test ~/Research/SQPhotstart/test/CUTE_examples/hs004
~/Research/SQPhotstart/bin/Release/simple_test ~/Research/SQPhotstart/test/CUTE_examples/hs006
~/Research/SQPhotstart/bin/Release/simple_test ~/Research/SQPhotstart/test/CUTE_examples/hs007
~/Research/SQPhotstart/bin/Release/simple_test ~/Research/SQPhotstart/test/CUTE_examples/hs008
~/Research/SQPhotstart/bin/Release/simple_test ~/Research/SQPhotstart/test/CUTE_examples/hs009
~/Research/SQPhotstart/bin/Release/simple_test ~/Research/SQPhotstart/test/CUTE_examples/hs010
~/Research/SQPhotstart/bin/Release/simple_test ~/Research/SQPhotstart/test/CUTE_examples/hs011
~/Research/SQPhotstart/bin/Release/simple_test ~/Research/SQPhotstart/test/CUTE_examples/hs012
~/Research/SQPhotstart/bin/Release/simple_test ~/Research/SQPhotstart/test/CUTE_examples/hs013
~/Research/SQPhotstart/bin/Release/simple_test ~/Research/SQPhotstart/test/CUTE_examples/hs014
~/Research/SQPhotstart/bin/Release/simple_test ~/Research/SQPhotstart/test/CUTE_examples/hs014
~/Research/SQPhotstart/bin/Release/simple_test ~/Research/SQPhotstart/test/CUTE_examples/hs016
~/Research/SQPhotstart/bin/Release/simple_test ~/Research/SQPhotstart/test/CUTE_examples/hs017
~/Research/SQPhotstart/bin/Release/simple_test ~/Research/SQPhotstart/test/CUTE_examples/hs018
~/Research/SQPhotstart/bin/Release/simple_test ~/Research/SQPhotstart/test/CUTE_examples/hs019
~/Research/SQPhotstart/bin/Release/simple_test ~/Research/SQPhotstart/test/CUTE_examples/hs020
~/Research/SQPhotstart/bin/Release/simple_test ~/Research/SQPhotstart/test/CUTE_examples/hs021
~/Research/SQPhotstart/bin/Release/simple_test ~/Research/SQPhotstart/test/CUTE_examples/hs022
~/Research/SQPhotstart/bin/Release/simple_test ~/Research/SQPhotstart/test/CUTE_examples/hs023
~/Research/SQPhotstart/bin/Release/simple_test ~/Research/SQPhotstart/test/CUTE_examples/hs024
~/Research/SQPhotstart/bin/Release/simple_test ~/Research/SQPhotstart/test/CUTE_examples/hs024
~/Research/SQPhotstart/bin/Release/simple_test ~/Research/SQPhotstart/test/CUTE_examples/hs026
~/Research/SQPhotstart/bin/Release/simple_test ~/Research/SQPhotstart/test/CUTE_examples/hs027
~/Research/SQPhotstart/bin/Release/simple_test ~/Research/SQPhotstart/test/CUTE_examples/hs028
~/Research/SQPhotstart/bin/Release/simple_test ~/Research/SQPhotstart/test/CUTE_examples/hs029
~/Research/SQPhotstart/bin/Release/simple_test ~/Research/SQPhotstart/test/CUTE_examples/hs020
~/Research/SQPhotstart/bin/Release/simple_test ~/Research/SQPhotstart/test/CUTE_examples/hs031
~/Research/SQPhotstart/bin/Release/simple_test ~/Research/SQPhotstart/test/CUTE_examples/hs032
~/Research/SQPhotstart/bin/Release/simple_test ~/Research/SQPhotstart/test/CUTE_examples/hs033
~/Research/SQPhotstart/bin/Release/simple_test ~/Research/SQPhotstart/test/CUTE_examples/hs034
~/Research/SQPhotstart/bin/Release/simple_test ~/Research/SQPhotstart/test/CUTE_examples/hs034
~/Research/SQPhotstart/bin/Release/simple_test ~/Research/SQPhotstart/test/CUTE_examples/hs036
~/Research/SQPhotstart/bin/Release/simple_test ~/Research/SQPhotstart/test/CUTE_examples/hs037
~/Research/SQPhotstart/bin/Release/simple_test ~/Research/SQPhotstart/test/CUTE_examples/hs038
~/Research/SQPhotstart/bin/Release/simple_test ~/Research/SQPhotstart/test/CUTE_examples/hs039
~/Research/SQPhotstart/bin/Release/simple_test ~/Research/SQPhotstart/test/CUTE_examples/hs040
~/Research/SQPhotstart/bin/Release/simple_test ~/Research/SQPhotstart/test/CUTE_examples/hs041
~/Research/SQPhotstart/bin/Release/simple_test ~/Research/SQPhotstart/test/CUTE_examples/hs042
~/Research/SQPhotstart/bin/Release/simple_test ~/Research/SQPhotstart/test/CUTE_examples/hs043
~/Research/SQPhotstart/bin/Release/simple_test ~/Research/SQPhotstart/test/CUTE_examples/hs044
~/Research/SQPhotstart/bin/Release/simple_test ~/Research/SQPhotstart/test/CUTE_examples/hs045
~/Research/SQPhotstart/bin/Release/simple_test ~/Research/SQPhotstart/test/CUTE_examples/hs046
~/Research/SQPhotstart/bin/Release/simple_test ~/Research/SQPhotstart/test/CUTE_examples/hs047
~/Research/SQPhotstart/bin/Release/simple_test ~/Research/SQPhotstart/test/CUTE_examples/hs048
~/Research/SQPhotstart/bin/Release/simple_test ~/Research/SQPhotstart/test/CUTE_examples/hs049
~/Research/SQPhotstart/bin/Release/simple_test ~/Research/SQPhotstart/test/CUTE_examples/hs050
~/Research/SQPhotstart/bin/Release/simple_test ~/Research/SQPhotstart/test/CUTE_examples/hs051
~/Research/SQPhotstart/bin/Release/simple_test ~/Research/SQPhotstart/test/CUTE_examples/hs052
~/Research/SQPhotstart/bin/Release/simple_test ~/Research/SQPhotstart/test/CUTE_examples/hs053
~/Research/SQPhotstart/bin/Release/simple_test ~/Research/SQPhotstart/test/CUTE_examples/hs054
~/Research/SQPhotstart/bin/Release/simple_test ~/Research/SQPhotstart/test/CUTE_examples/hs054
~/Research/SQPhotstart/bin/Release/simple_test ~/Research/SQPhotstart/test/CUTE_examples/hs056
~/Research/SQPhotstart/bin/Release/simple_test ~/Research/SQPhotstart/test/CUTE_examples/hs057
~/Research/SQPhotstart/bin/Release/simple_test ~/Research/SQPhotstart/test/CUTE_examples/hs059
~/Research/SQPhotstart/bin/Release/simple_test ~/Research/SQPhotstart/test/CUTE_examples/hs060
~/Research/SQPhotstart/bin/Release/simple_test ~/Research/SQPhotstart/test/CUTE_examples/hs061
~/Research/SQPhotstart/bin/Release/simple_test ~/Research/SQPhotstart/test/CUTE_examples/hs062
~/Research/SQPhotstart/bin/Release/simple_test ~/Research/SQPhotstart/test/CUTE_examples/hs063
~/Research/SQPhotstart/bin/Release/simple_test ~/Research/SQPhotstart/test/CUTE_examples/hs064
~/Research/SQPhotstart/bin/Release/simple_test ~/Research/SQPhotstart/test/CUTE_examples/hs064
~/Research/SQPhotstart/bin/Release/simple_test ~/Research/SQPhotstart/test/CUTE_examples/hs066
~/Research/SQPhotstart/bin/Release/simple_test ~/Research/SQPhotstart/test/CUTE_examples/hs067
~/Research/SQPhotstart/bin/Release/simple_test ~/Research/SQPhotstart/test/CUTE_examples/hs068
~/Research/SQPhotstart/bin/Release/simple_test ~/Research/SQPhotstart/test/CUTE_examples/hs069
~/Research/SQPhotstart/bin/Release/simple_test ~/Research/SQPhotstart/test/CUTE_examples/hs070
