language: cpp
sudo: required
compiler:
- gcc
os:
- linux
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-6
    - g++-6
before_install:
- export CC=/usr/bin/gcc-6
- export CXX=/usr/bin/g++-6
- sudo apt-get clean
- sudo rm -rf /var/lib/apt/lists/*
- sudo apt-get update 
- sudo apt-get install build-essential gfortran pkg-config liblapack-dev libblas-dev
- wget --tries=40 --retry-connrefused --waitretry=1 --no-check-certificate https://www.coin-or.org/download/source/Ipopt/Ipopt-3.12.12.tgz
- tar xvzf Ipopt-3.12.12.tgz
- mkdir third_party
- mv Ipopt-3.12.12 ./third_party/CoinIpopt
- cd ./third_party/CoinIpopt
- cd ThirdParty/Mumps
- "./get.Mumps"
- cd ../ASL
- "./get.ASL"
- cd ../..
- mkdir build
- cd build
- "../configure"
- make -j5
- sudo make install
- ls include/coin
- export IPOPT_ROOT_DIR=`pwd`
- echo $IPOPT_ROOT_DIR
  #- ls lib
- cd ../../../
- mkdir build && cd build && cmake -DIpopt=ON ..
script:
- make -j5
- ../bin/Release/simple_test ../test/CUTE_examples/HS/hs001
- ../bin/Release/simple_test ../test/CUTE_examples/HS/hs002
- ../bin/Release/simple_test ../test/CUTE_examples/HS/hs003
- ../bin/Release/simple_test ../test/CUTE_examples/HS/hs004
- ../bin/Release/simple_test ../test/CUTE_examples/HS/hs005
- ../bin/Release/simple_test ../test/CUTE_examples/HS/hs006
- ../bin/Release/simple_test ../test/CUTE_examples/HS/hs007
- ../bin/Release/simple_test ../test/CUTE_examples/HS/hs008
- ../bin/Release/simple_test ../test/CUTE_examples/HS/hs009
- ../bin/Release/simple_test ../test/CUTE_examples/HS/hs010
- cd ../
- ./get_code_cov.sh

after_success:
- bash <(curl -s https://codecov.io/bash) -t ec5f6253-3c2f-4e2f-be8e-bf208702ad71
